---
title: "Exploratory Data Analysis"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{exploratory-data-analysis}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

Get the training data, see `titanic_train` for more info.

```{r, message=FALSE}
library(titanic)
library(data.table)
library(ggplot2)

train <- titanic::titanic_train
train <- as.data.table(train)
str(train)
```

## Passanger Analysis

### Age

```{r}
ggplot(train, aes(Age, fill=Sex)) + geom_density(position='stack',alpha=0.5) +
  ggtitle('Density by Age and Sex')
```

There are some null age values...

```{r}
table(is.na(train$Age))
prop.table(table(is.na(train$Age)))
```

almost 20% of the observations are missing an age value.

```{r}
train <- titanic::impute_passenger_age(train)
train$AgeGroup <- cut(train$Age, breaks = c(0,17,30,40,50,65,80), labels = c('<17','18-30','31-40','41-50','51-65','>=66'))

ap <- ggplot(train, aes(x=Age, fill=Sex)) + geom_density(position = 'stack', alpha=0.5)

ap
```

```{r}
ag_plt_df <- train[, .(Survived=sum(Survived)), by=c('AgeGroup','Sex')]
ag_all_df <- train[, .(Survived=sum(Survived)), by=c('Age','Sex')]

ggplot(ag_plt_df, aes(x=AgeGroup,y=Survived, fill=Sex)) + geom_col() +
  coord_flip() + 
  labs(title = 'Count of Survived Passengers by Age Group and Sex')

ggplot(ag_all_df, aes(x=Age, y=Survived, colour=Sex)) + geom_point()
```

```{r}
ap + facet_wrap('Embarked') +
  
prop.table(table(train$Sex,train$Embarked))
```
