---
title: "models"
author: "Chris Bemben"
date: "9/5/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r cars}
library(rstan)
library(rstanarm)
library(magrittr)

simple_model <- stan_model('~/projectrepos/titanic/stan/mod001.stan')
print(simple_model)
```

Now generate some sample data

```{r pressure}
simple_fit <- sampling(
  simple_model,
  data = list(N=nrow(train), y=train$Age),
  cores = 4,
  seed = 123
)
```

```{r}
summary(simple_fit)
```

```{r}
library(bayesplot)
samp <- rstan::extract(simple_fit)

hist(samp$y_rep, freq=FALSE)
```

## Fit Logistic Regression

Age is only explanatory variable at this time.

```{r}
age_logit_mod <- stan_model(file = '~/projectrepos/titanic/stan/mod002-logit.stan')

age_logit_fit <- sampling(
  age_logit_mod,
  data = list( N = nrow(train), 
               x = train$Age, 
               y = train$Survived, 
               N_new = nrow(test),
               cores = 4,
               x_new=test$Age),
  seed = 111
)
```

```{r}
age_logit_ext <- rstan::extract(age_logit_fit)

par(mfrow = c(3,1))
hist(age_logit_ext$alpha, main = 'alpha param')
hist(age_logit_ext$beta, main = 'beta param')
hist(age_logit_ext$y_rep, main = 'simulated survival')
```

```{r}
posterior <- as.array(age_logit_fit)
bayesplot::mcmc_scatter(posterior, pars=c("alpha","beta"))
```

```{r}
bayesplot::mcmc_intervals(posterior, pars=c("alpha","beta"))
```

```{r}
#https://discourse.mc-stan.org/t/posterior-prediction-from-logit-regression/12217/2
postDF <- as.data.frame(age_logit_ext$y_new)
bayesplot::ppc_stat(y = as.integer(train$Survived[1:418]), yrep = as.matrix(postDF), stat = mean)
```

```{r}
bayesplot::ppc_stat_grouped(y = as.integer(train$Survived[1:418]), yrep = as.matrix(postDF), stat = mean, group = train$Pclass[1:418])
```
The passenger class shows heterogeneitiy across passenger class. However, the model assumes the same suvivial rate across classes.

```{r}
age_logit_hier_mod <- stan_model('~/projectrepos/titanic/stan/mod002-logit-hier.stan')
age_logit_hier_fit <- sampling(
              age_logit_hier_mod,
              data = list( N = nrow(train),
                           age = train$Age,
                           Pclass = 3,
                           pclass_idx = train$Pclass,
                           survival = train$Survived ),
              seed = 112,
              cores = 4)
```

The survival rate is similar to the actual data.

```{r}
print(age_logit_hier_fit, pars = c('alpha','beta'))
```

```{r}
age_logit_hier_ext <- rstan::extract(age_logit_hier_fit)
y_rep <- as.matrix(age_logit_hier_fit, pars = "y_rep")

ppc_stat_grouped(age_logit_hier_ext,
                 y = train$Survived,
                 yrep = y_rep[1:891,],
                 group = train$Pclass,
                 stat = "mean",
                 binwidth = 0.009)

```

Predict with new data
```{r}

beta_post <- age_logit_hier_ext$beta

# Function for simulating y based on new x
gen_quant_r <- function(age, Pclass) {
  alpha_post<- age_logit_hier_ext$alpha[,Pclass] #get intercept for class of passenger
  lin_comb <- sample(alpha_post, size = length(age)) + age*sample(beta_post, size = length(age))
  prob <- 1/(1 + exp(-lin_comb)) #inverse of logit link function
  out <- rbinom(length(age), 1, prob)
  return(out)
}

y_hat_tr <- gen_quant_r(train$Age, test$Pclass)
mean(y_hat_tr == train$Survived)
```

generate predictions on the test data
```{r}
y_hat <- gen_quant_r(test$Age, test$Pclass)

# Accuracy
pred_df <- data.frame(PassengerId = test$PassengerId, Survived=y_hat)
#write.csv(pred_df, file = "~/projectrepos/titanic/data/predict_20200918.csv", row.names = F)
```

